// Turns tools/data.json and tools/people.json (from the build_*.js scripts) into the files the app loads:
// ../data.js (const D) and ../people.js (const P).
const fs = require('fs');
const path = require('path');
const D = JSON.parse(fs.readFileSync(path.join(__dirname, 'data.json'), 'utf8'));
delete D.offeringHeads; delete D.candCount;
fs.writeFileSync(path.join(__dirname, '..', 'data.js'), '/* Generated by tools/make_data_js.js from the Coral Island Wiki (Fandom, CC BY-SA). */\nconst D = ' + JSON.stringify(D) + ';\n');
console.log('data.js written');
const pf = path.join(__dirname, 'people.json');
if (fs.existsSync(pf)) {
  fs.writeFileSync(path.join(__dirname, '..', 'people.js'), '/* Villager details: schedules, heart events, hangouts. Generated by tools/make_data_js.js from the Coral Island Wiki (CC BY-SA). */\nconst P = ' + fs.readFileSync(pf, 'utf8') + ';\n');
  console.log('people.js written');
}
