// Turns tools/data.json (from build_data.js) into ../data.js, the file the app loads.
const fs = require('fs'), path = require('path');
const D = JSON.parse(fs.readFileSync(path.join(__dirname, 'data.json'), 'utf8'));
delete D.offeringHeads; delete D.candCount;
fs.writeFileSync(path.join(__dirname, '..', 'data.js'), '/* Generated by tools/make_data_js.js from the Coral Island Wiki (Fandom, CC BY-SA). */\nconst D = ' + JSON.stringify(D) + ';\n');
console.log('data.js written');
